# Build, Run and Test Tartan EcoSystem
name: Build and Run Tartan
on:
  schedule:
    - cron: '30 23 * * *'  # Runs the workflow at midnight every day
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  # build and run for RISCV
  run_riscv_m1_tartan:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

       # installs tools, ninja, installs llvm and sets up sccahe
      - name: setup ubuntu
        uses:  ./.github/actions/setup_ubuntu_build
        with:
          llvm_version: 17
          llvm_build_type: RelAssert

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Python libraries and system dependencies
        run: |
          pip install --user requests numpy h5py Pillow
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y libblas-dev libopenblas64-dev libopenblas-dev libpthread-stubs0-dev libboost-all-dev

      - name: build riscv M1
        uses: ./.github/actions/do_build_ock/do_build_m1

      - name: Download Daily Release
        run: |
          wget "https://github.com/intel/llvm/releases/download/nightly-2023-11-22/sycl_linux.tar.gz"
          mkdir linux_nightly_release
          tar -xzf sycl_linux.tar.gz -C linux_nightly_release

      - name: Build portBLAS
        uses: ./.github/actions/build_portBLAS_action
        with:
          workspace: ${{ github.workspace }}

      - name: Build portDNN
        uses: ./.github/actions/build_portDNN_action
        with:
          workspace: ${{ github.workspace }}

      - name: Package Tartan Artifacts
        run: |
          ls
          tar -cvzf new_tartan.tar.gz build portDNN_build_dir portBLAS_build_dir

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tartan-build
          path: new_tartan.tar.gz

  build_and_run_networks:
    runs-on: ubuntu-22.04
    needs: run_riscv_m1_tartan
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: tartan-build

      - name: Untar artifacts
        run: |
          tar -xvzf new_tartan.tar.gz
          ls

      - name: Build vgg and resnet
        uses: ./.github/actions/build_vgg_resnet_action
        with:
          workspace: ${{ github.workspace }}